---
  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Creates a VPC with Managed NAT, Public/Private subnets"
  Parameters:
    vpccidrBlock:
      Type: String
      Default: "10.0.0.0/16"
    VPCName:
      Type: String
      Description: "Type the Name of VPC" 
      Default: "adnan-vpc-donottouch"
  Resources:
    VPC:
      Type: "AWS::EC2::VPC"
      Properties:
        EnableDnsSupport: 'false'
        EnableDnsHostnames: 'false'        
        CidrBlock: !Ref vpccidrBlock
        Tags:
        -   Key: foo
            Value: !Ref VPCName
    PublicSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select
          - 0
          - Fn::GetAZs: ""
        CidrBlock: !Select [0, !Cidr [!Ref vpccidrBlock, 16 , 8]]
        Tags:
          -
            Key: "Name"
            Value: !Join [ "-", [ !Select [0, !Split ["-", !Ref VPCName]], !Select [ 2, !Split [ ".", !Select [0, !Cidr [!Ref vpccidrBlock, 16 , 8]] ] ] , SN, PUB01, redzone ] ]
            #Value: !Join [ "-", [ !Select [0, !Split ["-", !Ref VPCName]] , !Select [2, !Split [".", !Ref vpccidrBlock]] ,SN-PUB01-redzone ] ]